<?php

$COUNTRY_NAMES = array(
    'AW' => array("aruba"),
    'AF' => array("afghanistan"),
    'AO' => array("angola"),
    'AI' => array("anguilla"),
    'AX' => array("aland islands"),
    'AL' => array("albania"),
    'AD' => array("andorra"),
    'AE' => array("united arab emirates", " uae", "emirati", "dubai"),
    'AR' => array("argentina"),
    'AM' => array("armenia"),
    'AS' => array("american samoa"),
    'AQ' => array("antarctica", "south pole"),
    'AF' => array("french southern territories"),
    'AG' => array("antigua and barbuda", "barbuda", "antigua"),
    'AU' => array("australia", "aussie", "australian"),
    'AT' => array("austria"),
    'AZ' => array("azerbaijan"),
    'BI'=> array("burundi"),
    'BE'=> array("belgium", "belgian", "flemish"),
    'BJ'=> array("benin"),
    'BD' => array("bangladesh"),
    'BG' => array("bulgaria"),
    'BH' => array("bahrain"),
    'BS' => array("bahamas"),
    'BA'=> array("bosnia and herzegovina", "bosnia", "herzegovina"),
    'BY'=> array("belarus"),
    'BZ'=> array("belize"),
    'BM'=> array("bermuda"),
    'BO'=> array("plurinational state of bolivia", "bolivia"),
    'BR' => array("brazil", "rio", "olympics"),
    'BB'=> array("barbados"),
    'BN'=> array("brunei darussalam"),
    'BT' => array("bhutan"),
    'BV'=> array("bouvet island"),
    'BW'=> array("botswana"),
    'CF'=> array("central african republic", "centrafrique"),
    'CA'=> array(
        "canada", "ottawa", "toronto", "montreal", "calgary", "ottawa",
        "alberta", "british columbia", "manitoba", "new brunswick",
        "newfoundland", "nova scotia", "ontario", "prince edward island",
        "quebec", "saskatchewan"),
    'CH'=> array("switzerland", "swiss"),
    'CL' => array("chile"),
    'CN' => array(
        "china", "beijing", "chinese", "beijing", "peking", "shanghai",
        "hong kong", "mandarin", "cpc"),
    'CI'=> array("cote d'ivoire", "ivory coast"),
    'CM'=> array("cameroon"),
    'CD'=> array("democratic republic of the congo", "congo"),
    'CG'=> array("congo"),
    'CK'=> array("cook islands"),
    'CO'=> array("colombia"),
    'KM'=> array("comoros"),
    'CR'=> array("costa rica"),
    'CU'=> array("cuba", "castro"),
    'KY'=> array("cayman islands", "cayman"),
    'CY'=> array("cyprus"),
    'CZ'=> array("czech republic", "czech"),
    'DE' => array("germany", "german", "merkel", "refugees"),
    'DM'=> array("dominica"),
    'DK'=> array("denmark"),
    'DO'=> array("dominican republic", "dominican"),
    'DZ'=> array("algeria", "algerie", "algiers"),
    'EC'=> array("ecuador"),
    'EG'=> array("egypt"),
    'ES'=> array("spain", "spanish"),
    'EE'=> array("estonia"),
    'ET'=> array("ethiopia"),
    'FI'=> array("finland", "finnish", "finn"),
    'FJ'=> array("fiji"),
    'FR'=> array("france", "french", "paris", "bastille"),
    'GB'=> array(
        "united kingdom", "england", "london", "u.k.", "uk", "britain",
        "great britain", "northern ireland", "scotland", "wales", "brexit", "cameron", "pound", "ukip", "royal", "elizabeth", "british"),
    'GH'=> array("ghana"),
    'GI'=> array("gibraltar"),
    'GN'=> array("guinea"),
    'GM'=> array("gambia"),
    'GRC'=> array("greece"),
    'GL'=> array("greenland"),
    'GT'=> array("guatemala"),
    'GU'=> array("guam"),
    'GY'=> array("guyana"),
    'HK'=> array("hong kong"),
    'HN'=> array("honduras"),
    'HR'=> array("croatia"),
    'HT'=> array("haiti"),
    'HU'=> array("hungary"),
    'ID'=> array("indonesia"),
    'IN' => array("india", "chennai", "TN", "tamil nadu", "delhi", "new delhi", "bangalore", "pune",
            "mumbai", "bombay", "modi", "bjp", "rss", "rupee", "hindi", "indian"),
    'IOT'=> array("british indian ocean territory", "Chagos Islands", "Chagos"),
    'IE' => array("ireland"),
    'IR'=> array("islamic republic of iran", "iran"),
    'IQ'=> array("iraq", "baghdad"),
    'ISL'=> array("iceland"),
    'IL'=> array("israel"),
    'IT' => array("italy"),
    'JM'=> array("jamaica"),
    'JO'=> array("jordan"),
    'JP' => array("japan", "tokyo"),
    'KZ'=> array("kazakhstan"),
    'KE'=> array("kenya"),
    'KH'=> array("cambodia"),
    'KP' => array("republic of korea", "south korea", "seoul", "korean", "kim", "dprk"),
    'KW'=> array("kuwait"),
    'LB'=> array("lebanon"),
    'LR'=> array("liberia"),
    'LY'=> array("libya"),
    'LK'=> array("sri lanka"),
    'LU'=> array("luxembourg"),
    'LV'=> array("latvia"),
    'MA'=> array("morocco"),
    'MC'=> array("monaco"),
    'MDG'=> array("madagascar"),
    'MDV'=> array("maldives"),
    'MX'=> array("mexico", "mexican"),
    'MH'=> array("marshall islands"),
    'ML'=> array("mali"),
    'MT'=> array("malta"),
    'MM'=> array("myanmar"),
    'ME'=> array("montenegro"),
    'MN'=> array("mongolia"),
    'MZ'=> array("mozambique"),
    'MU'=> array("mauritius"),
    'MY'=> array("malaysia"),
    'NA'=> array("namibia"),
    'NG'=> array("nigeria"),
    'NI'=> array("nicaragua"),
    'NL' => array("netherlands", "holland", "dutch", "flemish"),
    'NO' => array("norway", "norwegian", "oslo"),
    'NP' => array("nepal"),
    'NZ' => array("new zealand"),
    'OM'=> array("oman"),
    'PK' => array("pakistan"),
    'PA'=> array("panama"),
    'PE'=> array("peru"),
    'PH'=> array("philippines", "filipino"),
    'PG'=> array("papua new guinea"),
    'PL' => array("poland", "polish"),
    'PR'=> array("puerto rico", "puerto rican"),
    'KR' => array(
        "democratic people's republic of korea", "north korea", "kim jong-un",
        "kim jong un", "pyongyang"),
    'PT' => array("portugal"),
    'PY'=> array("paraguay"),
    'PS'=> array("state of palestine", "palestine", "gaza", "west bank"),
    'QA'=> array("qatar"),
    'RO'=> array("romania"),
    'RU' =>  array("russian federation", "russia", "putin", "moscow", "ruble", "ussr"),
    'RW'=> array("rwanda"),
    'SA'=> array("saudi arabia", "saudi"),
    'SD'=> array("sudan"),
    'SG'=> array("singapore"),
    'SL'=> array("sierra leone"),
    'SV'=> array("el salvador"),
    'SO'=> array("somalia"),
    'RS'=> array("serbia"),
    'SK'=> array("slovakia"),
    'SL'=> array("slovenia"),
    'SE'=> array("sweden", "swedish", "swede"),
    'SY'=> array("syrian arab republic", "syria"),
    'TH'=> array("thailand", "thai"),
    'TT'=> array("trinidad and tobago"),
    'TN'=> array("tunisia"),
    'TR' => array("turkey", "turkish", "erdogan"),
    'TV' => array("tuvalu"),
    'TW'=> array("province of china taiwan", "taiwan"),
    'TZ'=> array("united republic of tanzania", "tanzania"),
    'UG'=> array("uganda"),
    'UA'=> array("ukraine"),
    'UY'=> array("uruguay"),
    'US' => array(
        "united states", "u.s.a.", "america", "obama", "new york", "manhattan",
        "u.s.", "brooklyn", "silicon valley", "nsa", "nasa", "clinton",
        "washington", "usaid", "snowden", "texas", "california", "florida",
        "nyc", "broadway", " usa ", "trump", "hillary", "sanders", "apple", "google", "democrat", "republican", "american", "pentagon"),
    'UZ' => array("uzbekistan"),
    'VA' => array("holy see", "vatican", "pope", "catholic"),
    'VC'=> array("saint vincent and the grenadines", "saint vincent", "st vincent"),
    'VE'=> array("bolivarian republic of venezuela", "venezuela", "caracas"),
    'VG'=> array(
        "british virgin islands",  "tortola", "virgin gorda", "anegada",
        "jost van dyke"),
    'VI'=> array("u.s. virgin islands", "us virgin islands"),
    'VN'=> array("viet nam", "vietnam"),
    'WS' => array("samoa"),
    'YE' => array("yemen"),
    'ZA' => array("south africa"),
    'ZM' => array("zambia"),
    'ZW' => array("zimbabwe")
);



?>
